trufnetwork/adapters

pyproject.toml, src/tsn_adapters/tasks/argentina/scrape_zip.py, tests/test_github.py, tests/test_scrape_zip.py
- Introduced a new optional dependency for Argentina scraping in pyproject.toml.
- Added `DataItem` and `SepaPreciosWebScraper` classes for scraping historical SEPA prices from the specified dataset.
- Implemented methods for fetching resource and download links, along with date validation.
- Created unit tests for `DataItem` and `SepaPreciosWebScraper` to ensure functionality and error handling.
- Updated existing test files for consistency and improved error messages.
- fix #13
Use created tests
=> feat(argentina): fetch SEPA data

src/examples/gsheets/dynamic/dynamic_flow.py, src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/common/trufnetwork/tn.py, src/tsn_adapters/tasks/argentina/models/sepa/sepa_models.py, src/tsn_adapters/tasks/argentina/utils/processors/resource_processor.py, tests/argentina/test_sepa_models.py
- Added Unix timestamp support for TNAccessBlock read/write operations
- Enhanced type safety with overloaded method signatures
- Improved code formatting and readability across multiple files
- fix #46 
- Added Unix timestamp support for reading records
- Introduced new `insert_unix_tn_records` method
- Added overload decorators for better type safety
- Enhanced error handling and logging
- Standardized tag naming from 'tsn' to 'tn'
- Improved code formatting in dynamic_flow.py
- Enhanced test formatting and readability
Note this will require changes to `data-provider` repo. I'll apply on the next PR
=> feat: record handling with Unix timestamp support

src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/common/interfaces/target.py, src/tsn_adapters/tasks/argentina/flows/argentina_ingestor_flow.py, src/tsn_adapters/tasks/argentina/task_wrappers.py
- Made `data_provider` parameter optional across argentina flow
- Updated interfaces and implementations to support optional data provider
- Enhanced type safety with proper Optional typing
- Improved code formatting and readability
- fix [#48](https://github.com/trufnetwork/adapters/issues/48)
=> chore(argentina): optional data provider

pyproject.toml, src/tsn_adapters/blocks/tn_access.py
Add batch methods to insertions
- fix #55
- related to https://github.com/trufnetwork/node/issues/767
=> feat(tn_access): add batch insert methods for TN

src/tsn_adapters/tasks/argentina/flows/argentina_ingestor_flow.py, src/tsn_adapters/tasks/argentina/provider/data_processor.py, src/tsn_adapters/tasks/argentina/task_wrappers.py, tests/argentina/aggregate/test_category_price_aggregator.py
- Introduced a new task `task_get_and_transform_data` to streamline data fetching and transformation, improving modularity and clarity.
- Updated `argentina_ingestor_flow` to utilize the new task, enhancing parallel processing of data for multiple dates and improving error handling for uncategorized products.
- Implemented concurrency controls in data fetching and processing to optimize resource usage and performance.
- Refactored imports and improved type safety by utilizing `cast` for transformer types, ensuring better integration with Prefect workflows.
- Enhanced logging and error handling across tasks to improve traceability and debugging capabilities.
- fix #60 
- tested on a local flow
=> chore(argentina): enhanced caching

pyproject.toml, src/tsn_adapters/blocks/fmp.py, src/tsn_adapters/blocks/primitive_source_descriptor.py, src/tsn_adapters/common/trufnetwork/models/tn_models.py, src/tsn_adapters/flows/real_time_flow.py, tests/fmp/test_fmpblock_integration.py, tests/fmp/test_real_time_flow.py
- Added "pytest-timeout" to dev dependencies in pyproject.toml for improved test stability.
- Introduced the FMPBlock in src/tsn_adapters/blocks/fmp.py to integrate with the FMP API:
- Implements get_active_tickers to fetch active trading data.
- Implements get_batch_quote to retrieve batch quote data for specified symbols.
- Refactored and extended src/tsn_adapters/blocks/primitive_source_descriptor.py:
- Renamed PrimitiveSourcesDescriptor to PrimitiveSourcesDescriptorBlock for clarity.
- Added WritableSourceDescriptorBlock and S3SourceDescriptor to handle data writing.
- Added a new real-time market data sync flow in src/tsn_adapters/flows/real_time_flow.py:
- Orchestrates data fetching, processing, and insertion.
- Incorporates robust error handling and batching mechanisms.
- Created …
=> feat(FMP): real time ingestion flow

README.md, src/tsn_adapters/common/trufnetwork/tn.py, src/tsn_adapters/flows/stream_deploy_flow.py, tests/flows/test_stream_deploy_flow.py
resolves: https://github.com/trufnetwork/adapters/issues/95
This pull request introduces a new Prefect flow for deploying primitive streams and includes corresponding unit tests. The primary changes involve adding new functions for stream initialization and deployment, creating a deployment flow, and adding tests for the new functionality.
* [`src/tsn_adapters/common/trufnetwork/tn.py`](diffhunk://#diff-242c6777a1982296ba60f46863874e48eece8a1137810fa528aa47107efc42e3R88-R93): Added `task_init_stream` and `init_stream` functions to initialize streams after deployment.
* [`src/tsn_adapters/flows/stream_deploy_flow.py`](diffhunk://#diff-6533539a96359e2d2740083fd3022f2ed66c4c2f6a4ec3d9d9abeebe8308ccd5R1-R91): Created a new Prefect flow `deploy_streams_flow` to handle the deployment of …
=> chore: deploy stream from given url

docker-compose.yaml, pyproject.toml
Related:
- https://github.com/trufnetwork/truf-data-provider/issues/434
- https://github.com/trufnetwork/truf-data-provider/issues/433
=> chore: bump prefect version to 3.2.1

src/tsn_adapters/flows/fmp/historical_flow.py, src/tsn_adapters/flows/fmp/real_time_flow.py, tests/argentina/flows/test_preprocess_flow.py, tests/fixtures/test_trufnetwork.py, tests/fmp/test_real_time_flow.py
=> chore: correct function call from adapters

src/tsn_adapters/blocks/fmp.py, src/tsn_adapters/flows/fmp/real_time_flow.py, tests/fixtures/test_trufnetwork.py, tests/fmp/test_real_time_flow.py
- Improve FMP API quote processing to handle null prices gracefully
- Add null price filtering with detailed logging in `get_batch_quote` method
- Implement comprehensive error handling and reporting in real-time flow
- Update BatchQuoteShort schema to support nullable prices with non-negative constraints
- Add extensive test coverage for null price scenarios in real-time market data sync
---
- fix #128
=> feat(fmp): handle null price from real time ingestion

src/tsn_adapters/blocks/tn_access.py
resolves: https://github.com/trufnetwork/truf-data-provider/issues/491
This pull request introduces changes to the `tn_access.py` file to enhance the error handling mechanism by including a new `TNDbTimeoutError` exception. The most important changes include adding the new exception class, updating the retry conditions to account for database timeout errors, and modifying the error handling in various methods to raise the new exception appropriately.
Enhancements to error handling:
* [`src/tsn_adapters/blocks/tn_access.py`](diffhunk://#diff-e13ae36ae533c5ca006ffba34c3c9a23d1f9eed153e17e507bcbc05b1ef27e46R87-R113): Added the `TNDbTimeoutError` class to handle database timeout errors.
* [`src/tsn_adapters/blocks/tn_access.py`](diffhunk://#diff-e13ae36ae533c5ca006ffba34c3c9a23d1f9eed153e17e50 …
=> chore: retry mechanism for database timeout tasks

src/tsn_adapters/flows/fmp/real_time_flow.py
- Drop duplicate quotes based on stream_id
- wait for tx
---
fix #132
=> feat(fmp): Deduplicate before insert

pyproject.toml, src/tsn_adapters/blocks/tn_access.py, tests/blocks/test_split_and_insert_records.py, tests/blocks/test_stream_deployment_initialization.py, tests/fmp/test_historical_flow.py, tests/fmp/test_real_time_flow.py
- Replace `SafeTNClientProxy` with a `handle_tn_errors` decorator for better type safety
- Add `get_stream_type` method for robust stream existence and initialization checks
- Enhance `task_filter_deployed_streams` to use `get_stream_type` for stream verification
- Update test cases to validate new stream checking mechanism
- Simplify error handling across TNAccessBlock methods
---
- fix #134 
- all tests passing
=> refactor(tn_access): Improve error handling and stream verification

pyproject.toml, src/tsn_adapters/blocks/__init__.py, src/tsn_adapters/blocks/shared_types.py, src/tsn_adapters/blocks/stream_filtering.py, src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/common/trufnetwork/models/tn_models.py, src/tsn_adapters/flows/fmp/historical_flow.py, src/tsn_adapters/flows/fmp/real_time_flow.py, tests/blocks/test_split_and_insert_records.py, tests/blocks/test_stream_filtering.py, tests/blocks/test_tn_network_error.py, tests/fixtures/test_trufnetwork.py, tests/fmp/test_historical_flow.py
- Implemented a new divide-and-conquer algorithm for efficient stream filtering
- Enhanced FMP historical flow with configurable batch processing and chunked ticker handling
- Added comprehensive test coverage for new stream filtering functionality
- Fixed timezone-aware datetime comparison issues in FMP flows
- Improved error handling and logging throughout the codebase
- fix #141 
- Added extensive unit tests for the stream filtering functionality
- Updated and enhanced existing tests for FMP historical flow
- Tested with various batch sizes and ticker configurations
- Verified proper handling of timezone-aware datetime comparisons
- already deployed
=> feat: stream filtering & fmp enhancements

src/tsn_adapters/blocks/fmp.py
resolves: https://github.com/trufnetwork/truf-data-provider/issues/523
This PR adds ticker detail for `truf.network` purpose
tested with local file calling the class method.
[output.json](https://github.com/user-attachments/files/19119549/output.json)
=> feat(fmp): add ticker detail

src/tsn_adapters/blocks/fmp.py
resolves: https://github.com/trufnetwork/truf-data-provider/issues/523
=> fix: ticker detail nullable field

src/tsn_adapters/common/trufnetwork/tn.py
resolves: https://github.com/trufnetwork/adapters/issues/158
=> feat: insert records to multiple streams at once

src/examples/gsheets/utils.py, src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/common/trufnetwork/tn.py, src/tsn_adapters/flows/stream_deploy_flow.py, src/tsn_adapters/utils/tn_record.py, tests/blocks/test_split_and_insert_records.py, tests/blocks/test_stream_deployment_initialization.py, tests/blocks/test_stream_filtering.py, tests/blocks/test_tn_access_integration.py, tests/fixtures/test_trufnetwork.py, tests/flows/test_stream_deploy_flow.py
resolves https://github.com/trufnetwork/adapters/issues/160
=> feat: adjust TN block to new architecture

src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/flows/fmp/historical_flow.py, src/tsn_adapters/flows/fmp/real_time_flow.py, tests/fmp/test_fmpblock_integration.py, tests/fmp/test_historical_flow.py, tests/fmp/test_real_time_flow.py
resolves https://github.com/trufnetwork/adapters/issues/165
`python -m pytest tests/fmp/test_historical_flow.py`
=> feat: adjust FMP flow with updated TN block

src/tsn_adapters/flows/stream_deploy_flow.py
- Introduce a set to track already initialized stream IDs during batch processing, allowing for more efficient state marking.
- Update the logic to mark streams as deployed, incorporating both successfully processed streams and those already initialized, improving clarity in deployment reporting.
---
- fix #169
=>  fix(stream_deploy_flow): filtered deployed streams are included

src/examples/gsheets/dynamic/dynamic_flow.py, src/examples/gsheets/utils.py, src/tsn_adapters/common/trufnetwork/tn.py
resolves: https://github.com/trufnetwork/adapters/issues/175
=> feat: adjust examples to new TN block

src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/flows/stream_deploy_flow.py, src/tsn_adapters/tasks/argentina/flows/insert_products_flow.py, src/tsn_adapters/tasks/argentina/models/aggregated_prices.py, src/tsn_adapters/tasks/argentina/target/trufnetwork.py, tests/argentina/flows/test_full_pipeline_integration.py, tests/argentina/flows/test_insert_products_flow.py, tests/blocks/test_stream_deployment_initialization.py, tests/blocks/test_tn_access_integration.py, tests/fixtures/test_trufnetwork.py, tests/fmp/test_historical_flow.py
resolves: https://github.com/trufnetwork/adapters/issues/178
`python -m pytest tests/argentina/flows/test_full_pipeline_integration.py`
`python -m pytest tests/argentina/flows/test_insert_products_flow.py`
=> feat: adjust Argentina adapter to new architecture

README.md, pyproject.toml, src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/common/trufnetwork/tn.py, tests/blocks/test_stream_deployment_initialization.py
resolves: https://github.com/trufnetwork/truf-data-provider/issues/644
=> feat: deploy streams in batch

src/tsn_adapters/blocks/fmp.py, tests/fmp/test_fmpblock_contract.py
- fix https://github.com/trufnetwork/truf-network/issues/733
=> feat(fmp): add commodities list API

src/tsn_adapters/blocks/fmp.py, src/tsn_adapters/flows/fmp/historical_flow.py, src/tsn_adapters/flows/fmp/real_time_flow.py
=> chore(fmp): make volume nullable on quotes

src/tsn_adapters/blocks/fmp.py, src/tsn_adapters/blocks/tn_access.py, src/tsn_adapters/flows/fmp/historical_flow.py, src/tsn_adapters/flows/fmp/real_time_flow.py, src/tsn_adapters/utils/create_empty_df.py, tests/blocks/test_tn_access_filtering.py, tests/fmp/test_fmpblock.py, tests/fmp/test_fmpblock_contract.py, tests/fmp/test_fmpblock_integration.py, tests/fmp/test_historical_flow.py, tests/utils/fake_tn_access.py
applies these commits resolutions:
1f2262b: chore(fmp): make volume nullable on quotes (#192) …
0028196: feat(fmp): Introduce new data models and API endpoint (#185) …
58b3ed9: chore(v1): filter out zero-value records in `TNAccessBlock` (#187) …
c65a419: feat(fmp): add commodities list API (#188) …
8747c83: chore(fmp): permit to detect gaps in data (#190) …
- fix https://github.com/trufnetwork/truf-data-provider/issues/678
=> chore: merge recent changes from v1

pyproject.toml
resolves: https://github.com/trufnetwork/truf-data-provider/issues/716
=>  chore: bump truflation-data dependency
