trufnetwork/adapters

pyproject.toml
src/examples/gsheets/direct/direct_flow.py
src/examples/gsheets/dynamic/dynamic_flow.py
src/examples/gsheets/utils.py
src/tsn_adapters/tasks/github.py
src/tsn_adapters/tasks/tsn.py

- add pending updates forgotten on parallel branch, to increase flexibility of tasks (parameterized waiting)
- update SDK references
- tested in a [draft PR](https://github.com/trufnetwork/truf-data-provider/pull/342) to tsn-data-provider (install with no errors, run read)

chore: pending updates & updated sdk reference

---

src/tsn_adapters/tasks/argentina/aggregate/__init__.py
src/tsn_adapters/tasks/argentina/aggregate/category_price_aggregator.py
src/tsn_adapters/tasks/argentina/models/__init__.py
src/tsn_adapters/tasks/argentina/models/aggregated_prices.py
src/tsn_adapters/tasks/argentina/models/category_map.py
src/tsn_adapters/tasks/argentina/models/sepa_models.py

- Added new price aggregation functionality for Argentina SEPA data
- Implemented category-based price aggregation logic
- Created new Pandera models for data validation:
- `SepaProductCategoryMapModel` for product-category mapping
- `SepaAggregatedPricesModel` for aggregated price data
- Updated existing `SepaAvgPriceProductModel` to include date in grouping
- Reorganized model imports and documentation
- fix [#21](https://github.com/trufnetwork/adapters/issues/21)
It was used to create the [presented data](https://docs.google.com/spreadsheets/d/1fvYSw_PMtv-CJXS-3riwEzMKIodtwvlojA8VNeGQQCQ/edit?gid=77269284#gid=77269284)

feat(argentina): price aggregation functionality

---

pyproject.toml

This pull request includes an update to the `pyproject.toml` file to change the version of the `trufnetwork-sdk-py` dependency.
Dependency update:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L13-R13): Updated the `trufnetwork-sdk-py` dependency to use the commit `109cadf7c732c845ef074274d4af207256404602` instead of the previous commit `fa51592c87469078686df4d6df413ea24f4d475f`.

chore: bump truf.network python sdk version

---

pyproject.toml
src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/common/interfaces/target.py
src/tsn_adapters/tasks/argentina/flows/ingest_flow.py
src/tsn_adapters/tasks/argentina/target/trufnetwork.py
src/tsn_adapters/tasks/argentina/task_wrappers.py
tests/argentina/flows/test_preprocess_flow.py
tests/fmp/test_historical_flow.py
tests/fmp/test_real_time_flow.py

Refactors the TrufNetwork data insertion methods in `TNAccessBlock` and related tasks to improve efficiency and clarity.  The main changes include:
-   Introduced a unified `batch_insert_tn_records` method to handle both regular and unix timestamped data, replacing `batch_insert_unix_tn_records`. The `is_unix` flag controls the timestamp format.
-   Renamed `split_and_insert_records_unix` to `split_and_insert_records` and added the `is_unix` parameter.
-   Updated task wrappers and flows to use the new unified methods.
-   Added `batch_insert_data` to the `ITargetClient` interface and implemented it in `TrufNetworkClient`.  The old `insert_data` method is now deprecated.
-   Simplified the Argentina ingest flow (`ingest_flow.py`) by using the new batch insert method, removing redundant …

chore: argentina batch request & additional tests

---

src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/common/trufnetwork/models/tn_models.py
src/tsn_adapters/tasks/argentina/target/trufnetwork.py
tests/argentina/flows/test_preprocess_flow.py
tests/blocks/test_split_and_insert_records.py
tests/fixtures/test_trufnetwork.py

- Adds stream existence checks and data provider-aware batching for TrufNetwork records.
- Enhances error tracking with `failed_reasons` to pinpoint insertion failures.
- Introduces stream filtering to prevent insertion into non-existent streams.
- Refactors split-and-insert logic for improved reliability and retry handling.
- Fixes #100 
- Enhanced integration tests cover failure scenarios and mixed data providers.
- Unit tests were added to check the stream's existence.
- Tested filtering with deployed/non-deployed streams, including cache-based filtering.
- Improved test fixtures for better blockchain node startup handling.

feat: check deployed streams on insert

---

docker-compose.yaml
pyproject.toml
src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/common/trufnetwork/tn.py
src/tsn_adapters/flows/stream_deploy_flow.py

resolves: https://github.com/trufnetwork/truf-data-provider/issues/454
This pull request includes several updates and improvements to the `docker-compose.yaml`, `pyproject.toml`, and various Python files in the `src/tsn_adapters` directory. The most important changes include updating the Prefect image versions, modifying dependencies, and adding a new parameter to the `task_deploy_primitive` function and related calls.
Dependency and configuration updates:
* [`docker-compose.yaml`](diffhunk://#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9L16-R16): Updated Prefect image versions from `3.1.12` to `3.2.1` for both `prefect` and `prefect-worker` services. [[1]](diffhunk://#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9L16-R16) …

feat(adapter): deploy unix contract

---

pyproject.toml
src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/tasks/argentina/flows/ingest_flow.py
src/tsn_adapters/tasks/argentina/flows/preprocess_flow.py
src/tsn_adapters/tasks/argentina/target/trufnetwork.py

- Introduced `batch_insert_records_with_external_created_at` method for Truflation streams
- Updated insert tasks to support external created_at flag
- Implemented UTC timestamp generation for external created_at records
note: the place this PR is introducing data-provider specific code isn't the best. This path was taken to accelerate deploying of recent works
- fix #107

feat(tn_access): Add support for external created_at in record insertion

---

src/tsn_adapters/flows/stream_deploy_flow.py

- Remove explicit `tn_client` parameter from stream deployment functions
- Use `tna_block.get_client()` to dynamically retrieve the TN client
- Update `check_and_deploy_stream` to use account from TN access block
- Modify `deploy_streams_flow` to remove redundant client parameter
- Adjust method calls to use block-level client methods
- fix #111

chore: serializeable deploy flow

---

src/tsn_adapters/flows/stream_deploy_flow.py

- Introduce `is_unix` parameter to `deploy_streams_flow` function
- Pass `is_unix` flag to `check_and_deploy_stream` task for flexible stream deployment
- Enable Unix-specific stream deployment configuration
- fix #113

feat(stream_deploy_flow): Add param for Unix stream deployment

---

src/tsn_adapters/flows/stream_deploy_flow.py

the tn_client was removed, making it become null when passed, so we need to assign it again.
resolves: https://github.com/trufnetwork/adapters/issues/116
This pull request includes a small change to the `src/tsn_adapters/flows/stream_deploy_flow.py` file. The change refactors the way the `tn_client` is accessed to improve code readability and maintainability.
Refactoring for readability:
* [`src/tsn_adapters/flows/stream_deploy_flow.py`](diffhunk://#diff-6533539a96359e2d2740083fd3022f2ed66c4c2f6a4ec3d9d9abeebe8308ccd5L43-R44): Refactored the `check_and_deploy_stream` function to directly assign the `tn_client` variable before using it to get the current account.

fix: unable to deploy primitive stream

---

src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/common/trufnetwork/__init__.py
src/tsn_adapters/common/trufnetwork/models/tn_models.py
src/tsn_adapters/common/trufnetwork/tn.py
src/tsn_adapters/flows/stream_deploy_flow.py
tests/blocks/test_stream_deployment_initialization.py
tests/flows/test_stream_deploy_flow.py

- Introduce `deploy_stream` and `init_stream` methods in TNAccessBlock
- Add corresponding test cases for stream deployment and initialization
- Update stream deployment flow to use new block-level methods
- Refactor TN tasks to leverage block-level stream management
- Improve stream deployment flexibility with batched processing
---
- fix #115

feat(deploy_flow): include batching mechanism to avoid threads error

---

pyproject.toml
src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/flows/stream_deploy_flow.py
tests/blocks/test_tn_network_error.py
tests/flows/test_retry_behavior.py

- **SafeTNClientProxy Implementation**:  
Introduced a proxy wrapper (`SafeTNClientProxy`) for the TN client that intercepts method calls to catch TN network errors and re-raise them uniformly as `TNNodeNetworkError`.
- **Custom Retry Condition**:  
Added a new retry condition function `tn_special_retry_condition` that ensures:
- TN network errors are retried indefinitely.
- Non-network errors are only retried up to a maximum defined by the provided threshold.
- **Enhanced Error Handling in TNAccessBlock**:  
Updated the TNAccessBlock class to:
- Use the new `safe_client` property instead of directly calling `get_client()`.
- Wrap client instantiation in a try/except block to catch and re-raise network errors as `TNNodeNetworkError`.
- **Deployment Flow Improvements**:  
Modified …

feat(tn_access): Enhance network error handling and retry mechanism

---

src/tsn_adapters/common/trufnetwork/tn.py

- Enhance task reliability by adding retry configuration to TrufNetwork tasks
- Apply `UNUSED_INFINITY_RETRIES` and `tn_special_retry_condition` to `task_insert_tsn_records`, `task_deploy_primitive`, and `task_init_stream`
- Set consistent retry delay of 10 seconds and 3 retry attempts
- Improve error handling and network resilience for TrufNetwork operations
---
- fixes #124

feat(tn): Add retry mechanism to TrufNetwork tasks

---

src/tsn_adapters/blocks/deployment_state.py
tests/blocks/test_deployment_state.py

- Introduces a new Prefect Block for tracking deployment states of streams.
- Provides an abstract base class `DeploymentStateBlock` and a concrete implementation `S3DeploymentStateBlock`.
- `S3DeploymentStateBlock` uses an S3 bucket to store deployment states in a unified Parquet file, ensuring consistency.
- Uses Pandera DataFrameModel (`DeploymentStateModel`) to enforce schema validation for deployment state data.
- Includes comprehensive unit tests covering all key functionalities of `S3DeploymentStateBlock`.
- fix https://github.com/trufnetwork/truf-data-provider/issues/483
- Unit tests were added using `pytest` and `unittest.mock.MagicMock` to simulate S3 interactions.
- Tests cover marking single and multiple streams as deployed, checking deployment status, updating states, and …

feat: Add Deployment State Tracking Block

---

src/tsn_adapters/blocks/tn_access.py

Resolves: https://github.com/trufnetwork/truf-data-provider/issues/491
This pull request includes changes to the `src/tsn_adapters/blocks/tn_access.py` file to enhance the retry mechanism for several task functions. The most important changes involve adding retry parameters to the `@task` decorator to improve fault tolerance.
Enhancements to retry mechanism:
* [`src/tsn_adapters/blocks/tn_access.py`](diffhunk://#diff-e13ae36ae533c5ca006ffba34c3c9a23d1f9eed153e17e507bcbc05b1ef27e46L554-R554): Updated the `@task` decorator for `task_read_all_records` to include `retries=UNUSED_INFINITY_RETRIES`, `retry_delay_seconds=10`, and `retry_condition_fn=tn_special_retry_condition(5)`.
* [`src/tsn_adapters/blocks/tn_access.py`](diffhunk://#diff-e13ae36ae533c5ca006ffba34c3c9a23d1f9eed153e17e507bcbc05b1 …

chore: retry the failed tasks

---

src/tsn_adapters/blocks/tn_access.py

resolves: https://github.com/trufnetwork/adapters/issues/135
This pull request includes a minor change to the error handling logic in the `TNNodeNetworkError` class within the `tn_access.py` file. The change simplifies the condition that checks for specific error messages in `RuntimeError` instances.
* [`src/tsn_adapters/blocks/tn_access.py`](diffhunk://#diff-e13ae36ae533c5ca006ffba34c3c9a23d1f9eed153e17e507bcbc05b1ef27e46L74-R74): Modified the condition to check for the presence of "tcp" instead of "dial tcp" in the error message string.

chore: retry on network error even without the 'dial' text

---

src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/tasks/argentina/flows/preprocess_flow.py

This PR introduces concurrency improvements and refactors Argentina's preprocessing flow:
Core Changes:
- Add concurrency context managers for thread-safe access to TN resources
- Remove unnecessary parameter from Argentina preprocessing flow
- fix https://github.com/trufnetwork/adapters/issues/138
- Existing tests pass with the new concurrency managers
- Argentina preprocessing flow continues to work as expected after parameter removal

chore: additional concurrency manager and remove argentina param

---

src/tsn_adapters/blocks/tn_access.py

resolves: https://github.com/trufnetwork/adapters/issues/144
This pull request introduces a significant update to the `task_read_records` function in the `src/tsn_adapters/blocks/tn_access.py` file. The update aims to enhance the function's flexibility and robustness by allowing it to handle both ISO dates and Unix timestamps.
Enhancements to `task_read_records` function:
* Added support for both ISO dates and Unix timestamps by introducing the `is_unix` parameter, which determines the date format to be used.
* Updated the function signature to include a retry mechanism with specified retry conditions and delay.
* Included detailed docstrings to improve code documentation and clarity, outlining the function's arguments and return value.
* Implemented conditional logic to handle the …

fix: can't read records

---

pyproject.toml
src/tsn_adapters/flows/stream_deploy_flow.py
tests/fixtures/test_trufnetwork.py
tests/flows/test_stream_deploy_flow.py

This PR enhances the `deploy_streams_flow` to optionally integrate with a `DeploymentStateBlock`.
- **Optional Deployment State:** Added an optional `deployment_state: DeploymentStateBlock` parameter to `deploy_streams_flow`.
- **Stream Filtering:** When `deployment_state` is provided, the flow now filters out streams already marked as deployed (and verified to exist in TN) before processing batches, using the new `filter_deployed_streams_task`.
- **State Tracking:** Successfully deployed streams are now marked in the `DeploymentStateBlock` after each batch completes, using the new `mark_batch_deployed_task`. A single timestamp is used per batch.
- **Backward Compatibility:** The flow maintains its original behavior if the `deployment_state` parameter is not provided.
- **Dependency …

feat: Enhance deploy_streams_flow with `DeploymentStateBlock`

---

pyproject.toml
src/tsn_adapters/tasks/argentina/flows/__init__.py
src/tsn_adapters/tasks/argentina/flows/aggregate_products_flow.py
src/tsn_adapters/tasks/argentina/models/__init__.py
src/tsn_adapters/tasks/argentina/models/aggregate_products_models.py
src/tsn_adapters/tasks/argentina/provider/__init__.py
src/tsn_adapters/tasks/argentina/provider/product_averages.py
src/tsn_adapters/tasks/argentina/tasks/__init__.py
src/tsn_adapters/tasks/argentina/tasks/aggregate_products_tasks.py
src/tsn_adapters/utils/logging.py
tests/argentina/flows/test_aggregate_products_flow.py
tests/argentina/models/test_aggregate_products_models.py
tests/argentina/tasks/test_aggregate_products_tasks.py
tests/fixtures/test_trufnetwork.py

This PR introduces a new Prefect flow to aggregate product information from Argentina SEPA daily average price files. The goal is to create and maintain a persistent source descriptor list in S3, tracking each unique product and the date it was first observed. This aggregated list is required for downstream processes, such as the stream deployment flow.
**Key Changes:**
*   **New Flow:** Added `aggregate_argentina_products_flow` (`src/tsn_adapters/tasks/argentina/flows/aggregate_products_flow.py`) responsible for the end-to-end aggregation process.
*   **Data Models:**
*   Introduced `ProductAggregationMetadata` (Pydantic) to store processing state (last processed date, total product count).
*   Introduced `DynamicPrimitiveSourceModel` (Pandera) extending `PrimitiveSourceDataModel` to …

feat(argentina): Add product aggregation models and unit tests

---

.gitignore
pyproject.toml
src/tsn_adapters/blocks/stream_filtering.py
src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/common/trufnetwork/tn.py
src/tsn_adapters/flows/stream_deploy_flow.py
src/tsn_adapters/utils/__init__.py
tests/argentina/flows/test_full_pipeline_integration.py
tests/blocks/test_deployment_state.py
tests/blocks/test_prefect_task_error_catch.py
tests/blocks/test_sql_source_descriptor.py
tests/blocks/test_stream_deployment_initialization.py
tests/blocks/test_stream_filtering.py
tests/blocks/test_tn_network_error.py
tests/fixtures/test_trufnetwork.py
tests/flows/test_stream_deploy_flow.py
tests/integration/test_stream_deploy_flow_integration.py
tests/integration/test_stream_filtering_integration.py
tests/utils/fake_tn_access.py

* Introduced `FakeTNAccessBlock`: Created an in-memory fake implementation of `TNAccessBlock` in `tests/utils/fake_tn_access.py` to provide a more realistic and controllable testing environment for tasks interacting with the Truflation Network, reducing reliance on extensive mocking.
* Refactored Stream Filtering Logic:
* Improved the logic within `src/tsn_adapters/blocks/stream_filtering.py` for clarity and efficiency.
* Added `task_get_stream_states_divide_conquer` for scalable checking of stream deployment and initialization states, handling batching, fallbacks, and recursive checks.
* Updated Testing Strategy:
* Modified existing tests in `tests/blocks/test_stream_filtering.py` and `tests/flows/test_stream_deploy_flow.py` to utilize the new `FakeTNAccessBlock`, replacing previous …

feat(deployment): improve deploy workflow

---

src/tsn_adapters/blocks/models/sql_models.py
src/tsn_adapters/blocks/primitive_source_descriptor.py
src/tsn_adapters/blocks/sql_source_descriptor.py
src/tsn_adapters/tasks/argentina/flows/insert_products_flow.py
src/tsn_adapters/tasks/argentina/tasks/aggregate_products_tasks.py
tests/argentina/flows/test_aggregate_products_flow.py
tests/argentina/tasks/test_aggregate_products_tasks.py

- Add a nullable `source_display_name` column and model field; include in SQL queries.
- Map `productos_descripcion` to `source_display_name` in Argentina flows.
- Introduce `filter_deployed_streams` flag and pre-filter via `task_filter_initialized_streams`; remove redundant filtering.
- Update tests for `source_display_name`, refactor Prefect mocks, and enhance error handling.
- fix https://github.com/trufnetwork/truf-data-provider/issues/590

feat: Add `source_display_name` and stream init filtering

---

src/tsn_adapters/blocks/tn_access.py

Previously it is count as error, but it shouldn't
it make error no found being retried.

chore: empty result from no record instead of error

---

docker-compose.yaml
pyproject.toml

resolves: https://github.com/trufnetwork/truf-data-provider/issues/649
related: https://github.com/trufnetwork/truf-data-provider/pull/650
if not set, it will cause the version bumped to 3.4.1,
so I set it to the latest of 3.3.x

chore: bump prefect version to 3.3.7

---

src/tsn_adapters/blocks/fmp.py
src/tsn_adapters/utils/create_empty_df.py
tests/fmp/test_fmpblock.py
tests/fmp/test_fmpblock_contract.py
tests/fmp/test_fmpblock_integration.py

This PR refactors `FMPBlock` to use new FMP "stable" API endpoints, introduces bulk data fetching capabilities, enhances type safety with Pandera and nullable Pandas dtypes, and adds comprehensive unit and contract tests.
**Core Changes:**
*   **FMP Stable API Integration:**
*   Switched to FMP's `/stable/` API versions for existing calls and new bulk endpoints.
*   Introduced `FMPEndpoint` class for managing API path and parameters.
*   **New Bulk Data Fetching Methods:**
*   `get_equities(exchange)`: Fetches all stock quotes for an exchange (e.g., NYSE, NASDAQ).
*   `get_sp500_constituents()`: Retrieves S&P 500 constituents.
*   `get_cme_commodity_quotes()`: Gets batch commodity quotes.
*   Added `_fetch_fmp_list_data` helper for streamlined fetching and validation.
*   **Type Safety & …

feat(fmp): Introduce new data models and API endpoint

---

src/tsn_adapters/blocks/tn_access.py
tests/blocks/test_tn_access_filtering.py
tests/utils/fake_tn_access.py

- Import `force_sync` to handle synchronous result in `task_split_and_insert_records`.
- Introduce `_value_is_nonzero_str` helper to detect non-zero decimal strings.
- Filter out zero-value rows before insert and batch insert operations.
- Update logging to use `self.logger` with stream identifiers.
- Add `set_client` method to `FakeTNAccessBlock` for injecting mock clients.
- fix #186 
- Added unit tests in `tests/blocks/test_tn_access_filtering.py` covering:
- Mixed zero and non-zero values filtering.
- All-zero and empty DataFrame cases.

chore(v1): filter out zero-value records in `TNAccessBlock`

---

src/tsn_adapters/blocks/tn_access.py
src/tsn_adapters/flows/fmp/historical_flow.py
tests/fmp/test_historical_flow.py

- Introduce optional `after_date` parameter to `TNAccessBlock.get_earliest_date` and `TNAccessBlock.get_first_record`, enabling date-bound queries.
- Pass `after_date` to the TSN client (as Unix timestamp or ISO string) and propagate it through Prefect tasks and flows.
- Update historical flow tasks (`get_earliest_data_date`, pipeline) to forward `after_date` for consistent filtering.
- Enhance log messages with multi-line formatting when filtering out zero-value records.
- Set `wait=True` in `task_split_and_insert_records` calls to ensure synchronous record insertion.
- fix #189

chore(fmp): permit to detect gaps in data

---

src/tsn_adapters/blocks/fmp.py
tests/fmp/test_fmpblock_contract.py

- Introduce `IndexInfo` class to define the schema for stock market indexes from the FMP API, enhancing data structure clarity.
- Implement `get_index_list` method in `FMPBlock` to fetch available stock market indexes, ensuring robust error handling and type safety.
- Add integration test for `get_index_list` to validate functionality and ensure the returned DataFrame contains expected columns and data.
- Maintain existing functionality and type safety throughout the updates.
- fix https://github.com/trufnetwork/truf-data-provider/issues/680
new tests are ok

feat(fmp): add IndexInfo model and get_index_list method
